### SRD ROOT
GET http://localhost:4000/api

### SRD ALL CLASSES
GET http://localhost:4000/api/classes

### SRD ALL RACES
GET http://localhost:4000/api/races

### SRD ALL SPELLS FOR LEVEL
GET http://localhost:4000/api/spells?level=1

### SRD GET SPELL
GET http://localhost:4000/api/spells/burning-hands

### SRD GET ITEMS
GET http://localhost:4000/api/items

### SRD GET ITEM
GET http://localhost:4000/api/items/5

### LEVEL INFO
GET http://localhost:4000/api/level?xp=35500

### ALL CHARACTERS
GET http://localhost:4000/api/characters

### ALL CHARACTERS FOR OWNER
GET http://localhost:4000/api/characters?owner=clayton.yarborough@gmail.com

### SINGLE CHARACTER
GET http://localhost:4000/api/characters/Cx5B4G7COna1qvSFnoeq

### WATCH SINGLE CHARACTER
GET http://localhost:4000/api/characters/Cx5B4G7COna1qvSFnoeq?watch=true


### UPDATE CHARACTER
POST http://localhost:4000/api/characters 
Content-Type: application/json

{
    "id": "Cx5B4G7COna1qvSFnoeq",
    "owner": "wkgreen13@gmail.com",
    "name": "Ardair Storm Crow",
    "race": "Human",
    "class": "Wizard",
    "xp": 300
}

### NEW CHARACTER
POST http://localhost:4000/api/characters 
Content-Type: application/json

{
    "name": "Samson",
    "race": "Dwarf",
    "class": "Fighter",
    "xp": 300,
    "owner": "clayton.yarborough@gmail.com"
}

### GET AUTH USERS
GET http://localhost:4000/api/characters/Cx5B4G7COna1qvSFnoeq/auth-users

### CHECK AUTH FOR USER
GET http://localhost:4000/api/characters/Cx5B4G7COna1qvSFnoeq/auth-users?user=wkgreen1@gmail.com

### ADD AUTH USER
POST http://localhost:4000/api/characters/Cx5B4G7COna1qvSFnoeq/auth-users?user=captaincmy@gmail.com

### REMOVING AUTH USER
DELETE http://localhost:4000/api/characters/Cx5B4G7COna1qvSFnoeq/auth-users?user=captaincmy@gmail.com

### DELETE CHARACTER
DELETE http://localhost:4000/api/characters/6oHp62hgG0zeFPjwa8RB
