### SRD ROOT
GET http://localhost:4000/api

### SRD ALL SPELLS (paginated)
GET http://localhost:4000/api/spells

### LEVEL INFO
GET http://localhost:4000/api/level?xp=35500

### ALL CHARACTERS
GET http://localhost:4000/api/characters

### ALL CHARACTERS FOR OWNER
GET http://localhost:4000/api/characters?owner=clayton.yarborough@gmail.com

### SINGLE CHARACTER
GET http://localhost:4000/api/characters/Cx5B4G7COna1qvSFnoeq

### UPDATE CHARACTER
POST http://localhost:4000/api/characters 
Content-Type: application/json

{
    "id": "Cx5B4G7COna1qvSFnoeq",
    "owner": "wkgreen13@gmail.com",
    "name": "Ardair Storm Crow",
    "race": "Human",
    "class": "Wizard",
    "xp": 300
}

### NEW CHARACTER
POST http://localhost:4000/api/characters 
Content-Type: application/json

{
    "name": "Samson",
    "race": "Dwarf",
    "class": "Fighter",
    "xp": 300,
    "owner": "clayton.yarborough@gmail.com"
}

### DELETE CHARACTER
DELETE http://localhost:4000/api/characters/6oHp62hgG0zeFPjwa8RB
