# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: kjintroverted/go-node

    working_directory: ~/dungeon
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b8:78:e9:fe:e2:dc:58:45:d2:36:b5:5e:a1:4a:be:c0"
      - run: cd .. && git clone git@github.com:kjintroverted/dragon-ui.git
      - run: cd .. && git clone git@github.com:kjintroverted/dnd-build.git build
      - run: cd .. && cp build/secret_firebase.json dragon-ui/src/secret_auth_config.json
      - run: go build .
      - run: mv dungeon ../build
      - run: cd ../dragon-ui && npm i
      - run: cd ../dragon-ui && npm run build:heroku
      - run: rm -r ../build/app
      - run: cp -r ../dragon-ui/build ../build/app
      - run: cd ../build && git push
      