# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: kjintroverted/go-node

    working_directory: ~/dungeon
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints:
          - "e3:c2:9d:6c:a3:16:09:b9:5f:db:8d:7e:5a:dc:fc:7f"
      - run: cd .. && git clone git@github.com:kjintroverted/dragon-ui.git
      - run: cd .. && git clone git@github.com:kjintroverted/dnd-build.git build
      - run: cd .. && cp build/secret_firebase.json dragon-ui/src/secret_auth_config.json
      - run: go build .
      - run: mv dungeon ../build
      - run: cd ../dragon-ui && npm i
      - run: cd ../dragon-ui && npm run build:heroku
      - run: rm -r ../build/app
      - run: cp -r ../dragon-ui/build ../build/app
      - run: cd ../build && ls -la
      