# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: kjintroverted/go-node

    working_directory: ~/dungeon
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: git clone git@github.com:kjintroverted/dragon-ui.git ../dragon-ui
      - run: mkdir ../build
      - run: go build .
      - run: mv dungeon ../build
      - run: cd ../dragon-ui && npm i
      - run: cd ../dragon-ui && npm run build:heroku
      - run: rm -r ../build/app
      - run: cp -r ../dragon-ui/build ../build/app
      - run: cd ../build && ls -la
      